on: push

name: Integration

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Security Tools
        run: |
          TFSEC_VERSION=1.26.3
          GOSEC_VERSION=2.12.0

          ## INSTALL GOSEC ##
          curl -o gosec.tar.gz -L https://github.com/securego/gosec/releases/download/v${GOSEC_VERSION}/gosec_${GOSEC_VERSION}_linux_amd64.tar.gz
          tar xvf gosec.tar.gz
          sudo mv gosec /usr/local/bin

          ## INSTALL TFSEC ##
          curl -o tfsec -L https://github.com/aquasecurity/tfsec/releases/download/v${TFSEC_VERSION}/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin

  build:
    needs: [scan]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go_version:
          - 1.16
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Download Dependencies
        run: |
          go mod download
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -o myproject

  docker-build:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |
          docker build . -t docker_demo:pipeline
