on: push

name: Integration

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Security Tools
        run: |
          TFSEC_VERSION=1.26.3
          GOSEC_VERSION=2.12.0

          ## INSTALL GOSEC ##
          curl -o gosec.tar.gz -L https://github.com/securego/gosec/releases/download/v${GOSEC_VERSION}/gosec_${GOSEC_VERSION}_linux_amd64.tar.gz
          tar xvf gosec.tar.gz
          sudo mv gosec /usr/local/bin

          ## INSTALL TFSEC ##
          curl -o tfsec -L https://github.com/aquasecurity/tfsec/releases/download/v${TFSEC_VERSION}/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin

      - name: Scan with GoSec
        run: |
          gosec ./...
      - name: Scan with tfsec
        run: |
          tfsec -m HIGH
  build:
    needs: [scan]
    strategy
